# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Roman Levytskyy
email: "r.levyts@gmail.com"
description: >
  Ambitious and eager full stack web developer, looking to share my programming journey, as well as keep an organized list of projects in one place.
about_me: >
  I'm a recent DevBootcamp graduate going into programming from a mathematical background. I got into programming because I love making things, but in most cases that requires tools and a workshop. Now I can work anytime, anywhere with all the latest tools readily available at my fingertips.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://levytsroman.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
linked_in_link: "https://www.linkedin.com/in/levytsroman"
github_link: "https://www.github.com/levytsroman"
twitter_username: ""
google_analytics_id: 'UA-117297510-1'
select_options: clear-filters HTML5 CSS3 SCSS javaScript jQuery materialize charts.js React jekyll Ruby-on-Rails Sinatra front-end back-end finished current
sass:
  sass_dir: assets/css/main.css
  style: :nested

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
